### ISSUE TITLE
Updated mdesc version throws error for ErrorViz plot

### ISSUE THREAD

**Issue by aalokjha** [DataScienceSquad/model-describer#94]
I got an error today while running the Wine Quality example when I ran ErrorViz code. I had installed the updated model-describer version from PyPI. Attaching the error screen shot. Please look in to it. 
![2018-04-09_7-14-49](https://user-images.githubusercontent.com/5980282/38499737-83eff586-3bd6-11e8-8a25-b4af2c6b1c16.jpg)

**Comment by danielbyler** [comment]
Can you point us to the offending notebook so we can see the whole thing in context @aalokjha

**Comment by datawrestler** [comment]
@aalokjha what version of pandas do you have? Please make sure it's in compliance with the requirements file and run again. That should resolve it.

**Comment by aalokjha** [comment]
I updated the pandas version. But it still throws the same error.

**Comment by datawrestler** [comment]
@aalokjha which version of pandas do you have? In the same notebook you are executing the code, can you please run the following:

```python
import pandas as pd
pd.__version__
```
In the [documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.qcut.html) for pandas 0.22, duplicates is an accepted parameter. Your kernel might be misaligned from your system python.
